/**
 * Invoice number generation service.
 *
 * Numbers are generated by the `generate_invoice_number` Postgres function which
 * uses a row-level `UPDATE … RETURNING` to increment a per-(company, year) counter
 * atomically.  Concurrent calls for the same company+year are serialised at the
 * database level — no application-layer locking or retry logic is required.
 *
 * Format: YYYY/MM/NNN
 *   YYYY = 4-digit calendar year (taken from the database clock at call time)
 *   MM   = 2-digit calendar month (01-12)
 *   NNN  = 3-digit zero-padded sequence, resets at the start of each new year
 *
 * Example: 2026/05/001  →  2026/05/002  →  …  →  2026/05/999
 *          2027/01/001  (new year, counter resets)
 *
 * The function MUST only be called during a draft → issued status transition so
 * that gaps in the sequence are not created by abandoned drafts.
 */

import { getSupabaseServiceClient } from '@/lib/supabase/server';
export { formatInvoiceNumber, parseInvoiceNumber, isValidInvoiceNumber } from '@/lib/invoice-number-format';

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Atomically generate the next invoice number for `companyId`.
 *
 * Calls the `generate_invoice_number` Postgres RPC which uses a row-level lock
 * to guarantee uniqueness under concurrent load.
 *
 * @param companyId  UUID of the company issuing the invoice.
 * @param year       Override the year (defaults to current year on the DB clock).
 *                   Useful in tests; leave undefined in production.
 * @returns          Formatted invoice number, e.g. "2026/05/001".
 * @throws           Error if the database call fails.
 */
export async function generateInvoiceNumber(
  companyId: string,
  year?: number,
): Promise<string> {
  // Use the service client so this works inside server actions even when called
  // outside a user request context (e.g. background jobs, tests).
  const supabase = getSupabaseServiceClient();

  const { data, error } = await supabase.rpc('generate_invoice_number', {
    p_company_id: companyId,
    p_year:       year ?? null,
  });

  if (error) {
    throw new Error(`Invoice number generation failed: ${error.message}`);
  }

  if (!data) {
    throw new Error('Invoice number generation returned an unexpected value.');
  }

  return data;
}

/**
 * Read the current sequence counter without incrementing it.
 * Safe to call at any time; useful for admin displays.
 *
 * @returns The last-issued sequence number (0 if none issued yet this year).
 */
export async function peekInvoiceSequence(
  companyId: string,
  year?: number,
): Promise<number> {
  const supabase = getSupabaseServiceClient();

  const { data, error } = await supabase.rpc('peek_invoice_sequence', {
    p_company_id: companyId,
    p_year:       year ?? null,
  });

  if (error) {
    throw new Error(`Peek invoice sequence failed: ${error.message}`);
  }

  return data ?? 0;
}

